### ISSUE TITLE
Address issue of continuous vs discrete variables

### ISSUE THREAD

**Issue by dleehr** [NESCent/dplace#157]
From email:

> Just a quick one - how come some of the continuous variables in the database have codes associated with them?  What is the idea / purpose behind this?

Long story short: it’s a hack and should be revisited.

The first cultural dataset I had to load was EA, and if you look at the csv files (ea_codes, ea_variable_names+categories, ea_vals), they don’t distinguish between continuous or discrete, and some of the continuous variables have sentinel values like “-“ or “.”. There’s a GitHub issue for this (https://github.com/NESCent/dplace/issues/75) and I raised it at one of the meetings. So to get all the data loaded, the import populates the variables, the codes, and then the values. If the value corresponds to a code, it gets linked to it - the import script doesn’t know if a variable is continuous or discrete, just whether or not a value has a predefined code/description.

The binford data sets don’t have a continuous/discrete column either, but there is a convention in the CODE column for indicating if a variable is discrete (“1”,”2", “3") or continuous (“Number", “Percentage”). The import code doesn’t do much with this, it just reads the codes if they exist.

It’s probably a good idea to run through the variables and add a continuous or discrete column, and revisit how they’re stored/displayed. But for now, it’s a hack that uses the codes when they match (for discrete), but also saves the raw values (for continuous).

> I've been working on displaying continuous cultural variables on the phylogenies by binning them (at the moment it just divides the range into 5 bins).  It works for the continuous variables that don't have codes associated with them at the moment (it just checks if the variable has associated codes, and if not, it bins the data), but obviously I'll need to modify it to work for continuous variables that have associated codes.

It might be a good task for the group (maybe check with Kate) to add a column to the CSV files indicating what’s discrete and what’s continuous.

**Comment by SimonGreenhill** [comment]
Fixed in 763f523
