### ISSUE TITLE
DOM manipulation (d3js) should be performed in a directive

### ISSUE THREAD

**Issue by dleehr** [NESCent/dplace#165]
d3js is used to manipulate the DOM from a controller [tree.js](https://github.com/NESCent/dplace/blob/2136eddc7e83efcc37bf1c391cf0ae588db0ac3f/dplace_app/static/js/controllers/tree.js). Within angularjs, DOM manipulation by d3js should be done in a directive for safety.

http://odiseo.net/angularjs/proper-use-of-d3-js-with-angular-directives
http://ng-learn.org/2014/01/Dom-Manipulations/

**Comment by dleehr** [comment]
Came across this today:

http://www.pseudobry.com/building-large-apps-with-angular-js/ - see __3rd-party integration with AngularJS__
may be able to just use `$scope.$apply(...);` instead of directive

**Comment by stefelisabeth** [comment]
I think we can close this because I don't think I can use $scope.$apply(...) for this, since tree construction requires DOM manipulation and not changing scope variables.
