### ISSUE TITLE
Browser tabs are indistinguishable 

### ISSUE THREAD

**Issue by fionajordan** [NESCent/dplace#223]
Usability: All new tabs opened by a new action start with DPLACE, making it difficult for users to discern what tab corresponds to what page once a number of tabs are open. Once we have the DPLACE logo as the favicon can we remove DPLACE from the page titles as a way of resolving this issue?

**Comment by SimonGreenhill** [comment]
Yes, DPLACE should go to the end of the <title> attribute.
